const mongoose = require("mongoose");
const thoNhuongSchema = new mongoose.Schema({
  landId: String,
  nguoi_thuc_hien_1: String,
  thoi_gian_1: String,
  image_path_1: [String],
  loai_dat: String,
  asen_1: String,
  cadimi_1: String,
  chi_1: String,
  crom_1: String,
  dong_1: String,
  kem_1: String,
  ph_1: String,
  nguoi_thuc_hien_2: String,
  thoi_gian_2: String,
  image_path_2: [String],
  ph_2: String,
  oxy: String,
  chat_ran: String,
  sar: String,
  clorua: String,
  so4: String,
  bo: String,
  asen_2: String,
  cadimi_2: String,
  chi_2: String,
  crom_2: String,
  dong_2: String,
  kem_2: String,
  coli: String,
});

module.exports = mongoose.model("Tho_nhuong", thoNhuongSchema);
